name: ai_art
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  brain_fusion: ^0.0.8
  lottie: ^2.3.2
  url_launcher: ^6.1.10
  sentry_flutter: ^7.5.1
  iconsax: ^0.0.8
  shared_preferences: ^2.1.0
  flex_color_scheme: ^7.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  file_picker: ^5.2.11
  path: ^1.8.2
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.2
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_gen: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
